function ptwt = abspeed4(m)
load abspd2n2.dat; n=20;
a=abspd2n2(1:m,1);
b=abspd2n2(1:m,2);
rtb=sqrt(b);
rtb(m)=[];
t=diag(rtb,-1)+diag(a)+diag(rtb,1);
[f,lambda]=eig(t);
pt=diag(lambda);
for i=1:m
%wt(i)=sqrt(pi)*f(1,i)^2/4.d0; end
%wt(i)=f(1,i)^2.d0; end
%wt(i)=(4-2*i*pi-pi^2)*f(1,i)^2.d0; end
%pt(i) = -1* log(a(i));
%wt(i) = 1.^3 .* (b(i)/a(i));end
pt(i) = b(i);
wt(i)=a(i); end
%wt(i)=2*f(1,i)^2.d0; end
ptwt =[pt,wt'];